name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore RescueTimeStatus.csproj

    - name: Build
      run: dotnet build RescueTimeStatus.csproj -c ${{ matrix.configuration }} --no-restore

    - name: Execute unit tests
      run: dotnet test RescueTimeStatus.csproj -c ${{ matrix.configuration }} --no-build
